[package]
name = "ebpf-considered-harmful"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
color-eyre = "0.6.1"
libbpf-rs = "0.16.0"

[build-dependencies]
libbpf-cargo = "0.10.0"
